[toolchain]

[features]
resolution = true
skip-lint = false
# seeds = true

[programs.devnet]
voting_program = "51kgRBSnzQVTbK6jdgWj6NaXQ3gcyripUSW4kvAha3kd"

[programs.localnet]
voting_program = "E1iBq3vym5K5BuSm5v53oKKrQuQ4BTieCBJswg4PMGhi"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 10000